rm(list=ls())
load("cleaned_data.Rdata")
set.seed(20171005)
my_means <- tapply(bloodsamples_data$ir, list(bloodsamples_data$sex, bloodsamples_data$location), mean, na.rm=TRUE)
means_exercise_a <- my_means + matrix(rnorm(2*12), nrow=2)
save(list=c("bloodsamples_data", "means_exercise_a"), file="exam_1.Rdata")
rm(list=ls())
load("exam_1.Rdata")
ls()